apiVersion: v1
kind: Service
metadata:
  name:
    nginx-service
spec:
  type: LoadBalancer
  selector:
    type: general
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 5000
    targetPort: 5000
    name: phpmyadmin
  - port: 5050
    targetPort: 5050
    name: wp
  - port: 443
    targetPort: 443
    name: https
  - port: 22
    targetPort: 22
    name: ssh
  loadBalancerIP: 192.168.99.110
